import torch
import ctypes

# ---------------------------------------------------------------------
# 1. Load the shared library generated by CMake.
#    On Linux:   libgemm_op.so
#    On macOS:   libgemm_op.dylib
#    On Windows: gemm_op.dll
#
# The path below assumes the CMake build directory structure:
#   build/lib/libgemm_op.so
# ---------------------------------------------------------------------
lib = ctypes.CDLL('./build/lib/libgemm_op.so')

# ---------------------------------------------------------------------
# 2. Configure argument types for the exported C function:
#
#    void launch_gemm(
#        int8_t* A, int8_t* B, int32_t* C,
#        int M, int N, int K, int BATCH
#    );
#
# Pointers are passed as void* from Python, and integer sizes must
# match C-side int (usually 32-bit on all common platforms).
# ---------------------------------------------------------------------
lib.launch_gemm.argtypes = [
    ctypes.c_void_p,  # A pointer
    ctypes.c_void_p,  # B pointer
    ctypes.c_void_p,  # C pointer
    ctypes.c_int,     # M
    ctypes.c_int,     # N
    ctypes.c_int,     # K
    ctypes.c_int      # BATCH
]

# Optional: declare return type explicitly (defaults to int)
lib.launch_gemm.restype = None


# ---------------------------------------------------------------------
# 3. Prepare input tensors using PyTorch.
#
# Requirements:
#   • A: int8 tensor of shape [BATCH, M, K]
#   • B: int8 tensor of shape [BATCH, K, N]
#   • C: int32 tensor of shape [BATCH, M, N]
#
# Torch tensors must be on CPU and contiguous for raw pointer access.
# ---------------------------------------------------------------------
M, N, K, BATCH = 128, 128, 128, 1

A = torch.randint(-128, 127, (BATCH, M, K), dtype=torch.int8).contiguous()
B = torch.randint(-128, 127, (BATCH, K, N), dtype=torch.int8).contiguous()
C = torch.zeros((BATCH, M, N), dtype=torch.int32).contiguous()


# ---------------------------------------------------------------------
# 4. Call the C wrapper function.
#
# We pass the raw data pointer of Torch tensors to ctypes.
# launch_gemm will write results directly into C (in-place).
# ---------------------------------------------------------------------
lib.launch_gemm(
    ctypes.c_void_p(A.data_ptr()),
    ctypes.c_void_p(B.data_ptr()),
    ctypes.c_void_p(C.data_ptr()),
    M, N, K, BATCH
)

# ---------------------------------------------------------------------
# 5. Print the resulting tensor.
#    Since C was modified in place, the result is already in C.
# ---------------------------------------------------------------------
print(C)
